Reworked nodes rendering
kaaengine/kaacore pull request #108
Opened 2021-03-05 21:05 UTC by maniek2332

2021-04-15 18:53 UTC, labuzm requested changes

2021-04-15 18:53 UTC, labuzm commented on src/nodes.cpp
>          this->_mark_dirty();
Is this required? Visibility doesn't affect render data.

2021-04-15 18:53 UTC, labuzm commented on include/kaacore/draw_unit.h
> +    static inline StandardVertexData XY_UV(float x, float y, float u, float v)
Can we make this member function lowercase?

2021-04-15 18:53 UTC, labuzm commented on src/draw_unit.cpp
> +    KAACORE_ASSERT(
Is this really necessary?

2021-04-15 18:53 UTC, labuzm commented on src/draw_unit.cpp
> +    KAACORE_ASSERT(
The same as above, checking this in unit tests should sufficient.

2021-04-15 18:53 UTC, labuzm commented on include/kaacore/draw_unit.h
> +    static inline StandardVertexData XY_UV_MN(
The same as above.

2021-04-15 18:53 UTC, labuzm commented on src/draw_unit.cpp
> +            case DrawUnitModification::Type::insert:
Instead of updating the draw_units vector in-place, I would rather have a separate temp vector. We could use it to merge all the modifications with the original vector values and then swap the original vector with the new one.

2021-04-15 18:53 UTC, labuzm commented on src/nodes.cpp
>          this->_node_wrapper->on_detach();
Can we move this into `handle_remove_node_from_tree()`?

2021-04-15 18:53 UTC, labuzm commented on src/nodes.cpp
> +        key.program_raw_ptr = nullptr;
I think we should set default program pointer here.

2021-04-15 18:53 UTC, labuzm commented on src/nodes.cpp
>                  n->_node_wrapper->on_attach();
Can we move this into `handle_add_node_to_tree()`?

2021-04-15 18:53 UTC, labuzm commented on src/renderer.cpp
> +    key.views.each_active_internal_index([&](uint16_t view_internal_index) {
std::function will allocate memory on heap in this case, can we get rid of std::function and replace it with templated function?

2021-04-15 18:53 UTC, labuzm commented on include/kaacore/views.h
>      void each_active_z_index(const std::function<void(int16_t)>) const;
can we get rid of std::functions and replace them with templated functions?

2021-04-15 18:53 UTC, labuzm commented on include/kaacore/draw_unit.h
> +    void update_bucket(const ModsIter begin, const ModsIter end);
Is this used anywhere?

2021-04-15 18:53 UTC, labuzm commented on src/scenes.cpp
> +            auto [mod_1, mod_2] = node->calculate_draw_unit_updates();
Can we rename `mod_1` and `mod_2` to  `upsert_mod` and `remove_mod`?

2021-04-15 18:53 UTC, labuzm commented on src/scenes.cpp
> +Scene::resolve_dirty_nodes(const Scene::NodesQueue& processing_queue)
It seems that we can finally merge `resolve_dirty_nodes` and `update_nodes_drawing_queue` into one function :)

2021-04-15 18:53 UTC, labuzm commented on src/scenes.cpp
> +        get_engine()->renderer->process_view(view);
Can we grab pointer to renderer and reuse it?

2021-04-22 18:55 UTC, maniek2332 commented on src/nodes.cpp
>          this->_node_wrapper->on_detach();
`Scene::handle_remove_node_from_tree` handles stuff related to scene objects (e.g. spatial index, draw queue), it seems cleaner to handle Node's related callbacks here.

2021-04-22 18:57 UTC, maniek2332 commented on src/nodes.cpp
>                  n->_node_wrapper->on_attach();
Same as with `Scene::handle_remove_node_from_tree` - it seems cleaner to handle nodes callbacks in `Node::` method.

2021-04-27 16:21 UTC, labuzm approved these changes

2021-04-27 16:21 UTC, merged