introduce materials
kaaengine/kaacore pull request #109
Opened 2021-03-31 15:23 UTC by labuzm

2021-04-13 06:36 UTC, maniek2332 requested changes

2021-04-13 06:36 UTC, maniek2332 commented on include/kaacore/platform.h
> +enum class PlatforType { linux, osx, windows, unsupported };
typo - PlatformType

2021-04-13 06:36 UTC, maniek2332 commented on include/kaacore/resources_manager.h
> +#include <functional>
unused include

2021-04-13 06:36 UTC, maniek2332 commented on src/audio.cpp
> +    }
is this check needed?

2021-04-13 06:36 UTC, maniek2332 commented on src/platform.cpp
> +}
suggestion: use `#ifdef` with definitions generated by SDL_platform.h (`__LINUX__`, `__MACOSX__`, `__WINDOWS__`) instead of string comparison

2021-04-13 06:36 UTC, maniek2332 commented on src/renderer.cpp
> +        SDL_InitSubSystem(SDL_INIT_VIDEO) == 0,
Is this needed for bgfx to work? SDL Window doesn't seem to require it, as it get's created before renderer

2021-04-13 06:36 UTC, maniek2332 commented on src/renderer.cpp
> +            ->_uninitialize();
... `.res_ptr` lookup is no longer needed, as `ResourceReference` has `.get()`

2021-04-13 06:36 UTC, maniek2332 commented on include/kaacore/shaders.h
> +enum class ShaderModel { hlsl_dx9, hlsl_dx11, glsl, spriv, metal, unknown };
typo: `spirv`

2021-04-13 06:36 UTC, maniek2332 commented on src/shaders.cpp
> +    }
Is it guaranteed that two equal `ShaderModelMap` (`unordered_map`) instances will have the same elements ordering during iteration? Seems like it's [undefined behaviour](https://stackoverflow.com/questions/9856577/is-the-order-of-two-same-unordered-maps-the-same)

2021-04-15 20:47 UTC, labuzm commented on src/audio.cpp
> +    }
Yes, sdl_mixer doesn't support dummy driver.

2021-04-25 16:22 UTC, labuzm commented on src/renderer.cpp
> +            ->_uninitialize();
not really, `.get()` actually validates the resource and eventually throws exception and this point default materials are already uninitialized.

2021-04-25 17:34 UTC, labuzm commented on src/shaders.cpp
> +    }
well, I guess that's why it's called unordered_map :)

2021-05-06 18:39 UTC, maniek2332 approved these changes

2021-05-06 19:10 UTC, merged