fixed spatial index bug
kaaengine/kaacore pull request #122
Opened 2021-12-23 12:47 UTC by mmicek

2021-12-23 12:48 UTC, mmicek commented
Fix for bug: https://github.com/kaaengine/kaa/issues/132

2021-12-23 18:17 UTC, maniek2332 requested changes

2021-12-23 18:17 UTC, maniek2332 commented on demos/CMakeLists.txt
> +add_demo(demo-index-spatial index_spatial.cpp)
rename to: `demo-spatial-indexing-2` and `spatial_indexing_2` (or similiar)

2021-12-23 18:17 UTC, maniek2332 commented on demos/index_spatial.cpp
> +    std::vector<glm::dvec2> points;
unused variable

2021-12-23 18:17 UTC, maniek2332 commented on demos/index_spatial.cpp
> +    kaacore::NodePtr shape_repr;
unused variable

2021-12-23 18:17 UTC, maniek2332 commented on demos/index_spatial.cpp
> +        this->shape_repr = this->root_node.add_child(shape_repr);
unused variable

2021-12-23 18:17 UTC, maniek2332 commented on demos/index_spatial.cpp
> +                    KAACORE_LOG_DEBUG("Number of nodes: {}", query.size());
use `KAACORE_APP_LOG_INFO` to log application related messages

2021-12-23 18:17 UTC, maniek2332 commented on demos/index_spatial.cpp
> +#include <cstdlib>
unused include

2021-12-23 18:17 UTC, maniek2332 commented on demos/index_spatial.cpp
> +#include <vector>
unused include

2021-12-23 18:17 UTC, maniek2332 commented on demos/index_spatial.cpp
> +#include <glm/glm.hpp>
unused include

2021-12-27 13:31 UTC, maniek2332 approved these changes

2021-12-27 13:31 UTC, merged